const SUPABASE_URL="https://mncufdwicrlknhhkica.supabase.co",SUPABASE_KEY="sb_publishable_pK3jWDVlSe6moSxIBIHO2g_JNxnuA4O";
const PK="shasha_final_products_v1",SK="shasha_final_sales_v1",IK="shasha_final_invoice_v1",SYNC_KEY="shasha_final_pending_sync_v1";
let sbClient=null,products=[],sales=[],pending=[],cart=[],last=null,editing=null,scanner=null;
const money=n=>Number(n||0).toLocaleString("en-LK",{minimumFractionDigits:2,maximumFractionDigits:2});
const esc=s=>String(s??"").replace(/[&<>"']/g,x=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[x]));
const q=s=>String(s??"").replace(/\\/g,"\\\\").replace(/'/g,"\\'");
const read=(k,d)=>{try{let x=JSON.parse(localStorage.getItem(k)||"null");return x??d}catch{return d}};
function save(){localStorage.setItem(PK,JSON.stringify(products));localStorage.setItem(SK,JSON.stringify(sales))}
function savePending(){localStorage.setItem(SYNC_KEY,JSON.stringify(pending))}
function status(t,c="warn"){let e=document.getElementById("cloudStatus");if(e){e.textContent=t;e.className="statusbar "+c}}
function init(){products=read(PK,[]);sales=read(SK,[]);pending=read(SYNC_KEY,[]);renderProducts();renderCart();renderStock();renderSales();dashboard();updateSync();try{sbClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:false,autoRefreshToken:false}})}catch(e){status("⚠️ Supabase library unavailable — local mode","bad");return} status("☁️ Supabase connected — checking database…","warn");sbClient.from("products").select("id",{count:"exact",head:true}).then(({error})=>{if(error){status("⚠️ Supabase database check failed — sales remain local","bad")}else{status("☁️ Supabase database reachable ✓","ok");syncPendingSales()}})}
function tab(id,b){["bill","stock","sales","more"].forEach(x=>document.getElementById(x)?.classList.toggle("hidden",x!==id));document.querySelectorAll(".tab").forEach(x=>x.classList.remove("active"));b?.classList.add("active");if(id==="stock")renderStock();if(id==="sales")renderSales();if(id==="more"){dashboard();updateSync()}}
function nextInvoice(){let n=Number(localStorage.getItem(IK)||0)+1;localStorage.setItem(IK,n);return"INV-"+String(n).padStart(6,"0")}
function renderProducts(){let s=(document.getElementById("search")?.value||"").toLowerCase(),a=products.filter(p=>[p.name,p.barcode,p.partNo,p.category].join(" ").toLowerCase().includes(s)),r=document.getElementById("results");if(!r)return;r.innerHTML=a.map(p=>`<div class="product"><div class="product-name">${esc(p.name)}</div><div class="muted">${esc(p.barcode)} • Stock: <b>${p.stock||0}</b> • Sell: <b>Rs. ${money(p.sell)}</b> ${!Number(p.sell)?'<span class="badge zero">PRICE NOT SET</span>':""}</div><button class="blue" style="width:100%;margin-top:7px" onclick="add('${q(p.barcode)}')">Add</button></div>`).join("")||'<p class="muted">No products found.</p>'}
function add(b){let p=products.find(x=>String(x.barcode)===String(b));if(!p||Number(p.stock)<=0)return alert("Out of stock");if(!Number(p.sell))return alert("Selling price not set for "+p.name);let c=cart.find(x=>String(x.b)===String(b));if(c){if(c.qty>=p.stock)return alert("Not enough stock");c.qty++}else cart.push({b,qty:1});renderCart()}
function del(b){cart=cart.filter(x=>String(x.b)!==String(b));renderCart()}
function setQty(b,v){let p=products.find(x=>String(x.barcode)===String(b)),c=cart.find(x=>String(x.b)===String(b));if(!p||!c)return;c.qty=Math.max(1,Math.min(Math.floor(Number(v)||1,Number(p.stock))));renderCart()}
function renderCart(){let box=document.getElementById("cart");if(!box)return;let sub=0;box.innerHTML=cart.map(c=>{let p=products.find(x=>String(x.barcode)===String(c.b));if(!p)return"";let t=p.sell*c.qty;sub+=t;return`<div class="cart-item"><div><b>${esc(p.name)}</b><div class="muted">${esc(p.barcode)} × Rs. ${money(p.sell)}</div></div><input type="number" min="1" max="${p.stock}" value="${c.qty}" onchange="setQty('${q(c.b)}',this.value)"><div>Rs. ${money(t)}</div><button class="red" onclick="del('${q(c.b)}')">×</button></div>`}).join("")||'<p class="muted">Bill is empty.</p>';let d=Math.max(0,Number(document.getElementById("discount")?.value)||0),tot=Math.max(0,sub-d);document.getElementById("grand").textContent=money(tot);let pay=document.getElementById("payment")?.value,cash=Number(document.getElementById("cash")?.value)||0;document.getElementById("change").textContent=pay==="CASH"&&cash>=tot?"Change: Rs. "+money(cash-tot):""}
["discount","cash","payment"].forEach(id=>document.getElementById(id)?.addEventListener("input",renderCart));
function enqueue(s){let x=pending.find(r=>r.invoice===s.invoice);if(x){x.sale=s;x.items=s.items}else pending.push({invoice:s.invoice,sale:s,items:s.items,attempts:0});savePending();updateSync()}
function updateSync(){let e=document.getElementById("syncInfo");if(e)e.textContent=pending.length?pending.length+" sale(s) waiting for cloud sync.":"No pending sales."}
async function completeSale(){if(!cart.length)return alert("Bill is empty");let sub=cart.reduce((a,c)=>{let p=products.find(x=>String(x.barcode)===String(c.b));return a+(p?p.sell*c.qty:0)},0),discount=Math.max(0,Number(document.getElementById("discount").value)||0);if(discount>sub)return alert("Discount exceeds subtotal");let total=sub-discount,payment=document.getElementById("payment").value,cash=Number(document.getElementById("cash").value)||0;if(payment==="CASH"&&cash<total)return alert("Cash received is less than total");for(let c of cart){let p=products.find(x=>String(x.barcode)===String(c.b));if(!p||p.stock<c.qty)return alert("Not enough stock");if(!p.sell)return alert("Selling price not set for "+p.name)}
let items=cart.map(c=>{let p=products.find(x=>String(x.barcode)===String(c.b));return{barcode:p.barcode,name:p.name,qty:c.qty,cost:Number(p.cost||0),sell:Number(p.sell||0),total:p.sell*c.qty}}),sale={invoice:nextInvoice(),date:new Date().toISOString(),customer:document.getElementById("customer").value.trim(),phone:document.getElementById("phone").value.trim(),items,subtotal:sub,discount,total,payment,cash,change:payment==="CASH"?Math.max(0,cash-total):0,profit:items.reduce((a,i)=>a+(i.sell-i.cost)*i.qty,0)-discount};
items.forEach(i=>{let p=products.find(x=>String(x.barcode)===String(i.barcode));p.stock-=i.qty});sales.push(sale);enqueue(sale);save();cart=[];["customer","phone","discount","cash"].forEach(id=>document.getElementById(id).value=id==="discount"||id==="cash"?"":document.getElementById(id).value);document.getElementById("discount").value=0;document.getElementById("cash").value=0;renderCart();renderProducts();renderStock();renderSales();dashboard();show(sale);await syncPendingSales()}
async function ensureProduct(i){let b=String(i.barcode);let f=await sbClient.from("products").select("*").eq("barcode",b).maybeSingle();if(f.error)throw f.error;if(f.data)return f.data;let p=products.find(x=>String(x.barcode)===b)||i;let r=await sbClient.from("products").insert({barcode:b,part_no:p.partNo||null,name:p.name||i.name,buy:Number(p.cost||i.cost||0),sell:Number(p.sell||i.sell||0),stock:Number(p.stock||0),min_stock:Number(p.min??2)}).select().single();if(!r.error)return r.data;let retry=await sbClient.from("products").select("*").eq("barcode",b).maybeSingle();if(retry.error||!retry.data)throw r.error;return retry.data}
async function syncOne(r){let s=r.sale,cps={};for(let i of r.items)cps[i.barcode]=await ensureProduct(i);let f=await sbClient.from("sales").select("id").eq("invoice",s.invoice).maybeSingle();if(f.error)throw f.error;let sid=f.data?.id;if(!sid){let x=await sbClient.from("sales").insert({invoice:s.invoice,sale_time:s.date,subtotal:s.subtotal,discount:s.discount,total:s.total,profit:s.profit,payment:s.payment,cash:s.cash,balance:s.payment==="CREDIT"?s.total:s.change,customer:s.customer||null,phone:s.phone||null}).select("id").single();if(x.error){let z=await sbClient.from("sales").select("id").eq("invoice",s.invoice).maybeSingle();if(z.error||!z.data)throw x.error;sid=z.data.id}else sid=x.data.id}
let ex=await sbClient.from("sale_items").select("barcode").eq("sale_id",sid);if(ex.error)throw ex.error;let have=new Set((ex.data||[]).map(x=>String(x.barcode)));let missing=r.items.filter(i=>!have.has(String(i.barcode))).map(i=>({sale_id:sid,product_id:cps[i.barcode].id,barcode:i.barcode,name:i.name,qty:i.qty,unit_price:i.sell,buy_price:i.cost,total:i.total,profit:(i.sell-i.cost)*i.qty}));if(missing.length){let x=await sbClient.from("sale_items").insert(missing);if(x.error)throw x.error}
for(let i of r.items){let cp=cps[i.barcode],note="Sale "+s.invoice;let mv=await sbClient.from("stock_movements").select("id").eq("product_id",cp.id).eq("note",note).maybeSingle();if(mv.error)throw mv.error;if(mv.data)continue;let cur=await sbClient.from("products").select("stock").eq("id",cp.id).single();if(cur.error)throw cur.error;let old=Number(cur.data.stock||0),qty=Number(i.qty);if(old<qty)throw new Error("Cloud stock conflict for "+i.name);let up=await sbClient.from("products").update({stock:old-qty}).eq("id",cp.id).eq("stock",old).select("id").maybeSingle();if(up.error)throw up.error;if(!up.data)throw new Error("Cloud stock changed on another device. Sale kept locally.");let ins=await sbClient.from("stock_movements").insert({product_id:cp.id,barcode:i.barcode,movement_type:"OUT",qty,note});if(ins.error)throw ins.error}}
async function syncPendingSales(){if(!sbClient){return}if(!pending.length){updateSync();return}status("☁️ Syncing pending sales…","warn");for(let r of [...pending]){try{r.attempts++;savePending();await syncOne(r);pending=pending.filter(x=>x.invoice!==r.invoice);savePending()}catch(e){r.lastError=e.message||String(e);savePending();status("⚠️ Saved locally; cloud sync failed. Tap Sync Pending Sales after fixing Supabase.","bad");break}}updateSync();if(!pending.length)status("☁️ All sales synced to Supabase ✓","ok")}
async function loadProductsFromSupabase(alertIt){if(!sbClient)return alert("Supabase unavailable");try{let r=await sbClient.from("products").select("id,barcode,name,part_no,buy,sell,stock,min_stock").order("id");if(r.error)throw r.error;let local=new Map(products.map(p=>[String(p.barcode),p])),merged=[],cloud=new Set();for(let x of r.data||[]){let b=String(x.barcode);cloud.add(b);let o=local.get(b)||{};merged.push({...o,id:x.id,barcode:b,partNo:x.part_no||"",name:x.name,cost:Number(x.buy),sell:Number(x.sell),stock:Number(x.stock),min:Number(x.min_stock)})}for(let p of products)if(p.barcode&&!cloud.has(String(p.barcode)))merged.push(p);products=merged;save();renderProducts();renderStock();dashboard();if(alertIt)alert("Cloud products loaded: "+(r.data?.length||0))}catch(e){if(alertIt)alert("Cloud product load failed: "+e.message)}}
async function loadCloudSales(){if(!sbClient)return alert("Supabase unavailable");let r=await sbClient.from("sales").select("*").order("id",{ascending:false}).limit(100);if(r.error)return alert(r.error.message);for(let s of r.data||[]){let x=sales.find(z=>z.invoice===s.invoice);if(x)Object.assign(x,{date:s.sale_time,total:Number(s.total),profit:Number(s.profit),payment:s.payment,customer:s.customer||""});else sales.push({invoice:s.invoice,date:s.sale_time,total:Number(s.total),profit:Number(s.profit),payment:s.payment,customer:s.customer||"",subtotal:Number(s.subtotal),discount:Number(s.discount),cash:Number(s.cash),change:Number(s.balance),items:[]})}save();renderSales();dashboard();alert("Cloud sales loaded.")}
function renderStock(){let s=(document.getElementById("stockSearch")?.value||"").toLowerCase(),l=document.getElementById("stockList");if(!l)return;l.innerHTML=products.filter(p=>[p.name,p.barcode,p.partNo].join(" ").toLowerCase().includes(s)).map(p=>`<div class="product"><div class="product-name">${esc(p.name)}</div><div>${esc(p.barcode)} • Stock: <span class="badge ${p.stock<=p.min?"low":""}">${p.stock||0}</span> • Cost Rs. ${money(p.cost)} • Sell Rs. ${money(p.sell)}</div><button class="blue" style="width:100%;margin-top:8px" onclick="editProduct('${q(p.barcode)}')">✏️ EDIT PRODUCT</button></div>`).join("")||'<p class="muted">No products found.</p>'}
function renderSales(){let l=document.getElementById("salesList");if(!l)return;l.innerHTML=sales.slice().reverse().map(s=>`<div class="product"><div class="product-name"><a href="#" onclick="openSale('${q(s.invoice)}');return false">${esc(s.invoice)}</a></div><div>${new Date(s.date).toLocaleString()} • Rs. ${money(s.total)} • Profit Rs. ${money(s.profit)} ${s.customer?"• "+esc(s.customer):""}</div></div>`).join("")||'<p class="muted">No sales yet.</p>'}
function dashboard(){let d=new Date().toDateString(),a=sales.filter(s=>new Date(s.date).toDateString()===d);document.getElementById("ts").textContent="Rs. "+money(a.reduce((x,s)=>x+Number(s.total||0),0));document.getElementById("tp").textContent="Rs. "+money(a.reduce((x,s)=>x+Number(s.profit||0),0));document.getElementById("tb").textContent=a.length;document.getElementById("lc").textContent=products.filter(p=>Number(p.stock)<=Number(p.min)).length}
function editProduct(b){let p=products.find(x=>String(x.barcode)===String(b));if(!p)return;editing=p.barcode;["pb","pp","pn","pg","pcost","psell","pstock","pmin"].forEach((id,i)=>document.getElementById(id).value=[p.barcode,p.partNo||"",p.name,p.category||"",p.cost||0,p.sell||0,p.stock||0,p.min??2][i]);document.getElementById("pb").readOnly=true;document.querySelector('[onclick="saveProduct()"]').textContent="UPDATE PRODUCT";document.getElementById("pmsg").textContent="Editing: "+p.name;tab("more",document.querySelectorAll(".tab")[3])}
function clearForm(){["pb","pp","pn","pg","pcost","psell","pstock"].forEach(id=>document.getElementById(id).value="");document.getElementById("pmin").value=2;editing=null;document.getElementById("pb").readOnly=false;document.querySelector('[onclick="saveProduct()"]').textContent="SAVE PRODUCT";document.getElementById("pmsg").textContent=""}
async function saveProduct(){let v=id=>document.getElementById(id).value,b=v("pb").trim(),name=v("pn").trim();if(!b||!name)return alert("Barcode and name required");let p={...(editing?products.find(x=>x.barcode===editing):{}),barcode:b,partNo:v("pp").trim(),name,category:v("pg").trim(),cost:Number(v("pcost"))||0,sell:Number(v("psell"))||0,stock:Number(v("pstock"))||0,min:Number(v("pmin"))||2};if(editing)products[products.findIndex(x=>x.barcode===editing)]=p;else{if(products.some(x=>String(x.barcode)===b))return alert("Duplicate barcode");products.push(p)}save();renderProducts();renderStock();dashboard();document.getElementById("pmsg").textContent="Saved locally ✓";if(sbClient)try{let r=await sbClient.from("products").upsert({barcode:b,part_no:p.partNo||null,name:p.name,buy:p.cost,sell:p.sell,stock:p.stock,min_stock:p.min},{onConflict:"barcode"}).select().single();if(r.error)throw r.error;document.getElementById("pmsg").textContent="Saved to Supabase ✓";}catch(e){console.warn(e)}editing=null;clearForm()}
function openSale(i){let s=sales.find(x=>x.invoice===i);if(s){last=s;show(s)}}
function show(s){document.getElementById("receipt").innerHTML=`<div class="center"><b>SHASHA MOTORS POS</b><br>7/1A, Thambilwaththa, Makandana,<br>Piliyandala<br>0771112344</div><div class="hr"></div><div class="line"><span>Invoice</span><b>${esc(s.invoice)}</b></div><div class="line"><span>Date</span><span>${new Date(s.date).toLocaleString()}</span></div>${s.customer?`<div class="line"><span>Customer</span><span>${esc(s.customer)}</span></div>`:""}<div class="hr"></div>${(s.items||[]).map(i=>`<div><b>${esc(i.name)}</b><div class="line"><span>${i.qty} × Rs. ${money(i.sell)}</span><span>Rs. ${money(i.total)}</span></div></div>`).join("")}<div class="hr"></div><div class="line"><span>Subtotal</span><span>Rs. ${money(s.subtotal)}</span></div><div class="line"><span>Discount</span><span>Rs. ${money(s.discount)}</span></div><div class="line"><b>Grand Total</b><b>Rs. ${money(s.total)}</b></div><div class="line"><span>Payment</span><span>${esc(s.payment)}</span></div>${s.payment==="CASH"?`<div class="line"><span>Cash</span><span>Rs. ${money(s.cash)}</span></div><div class="line"><span>Change</span><span>Rs. ${money(s.change)}</span></div>`:""}<div class="hr"></div><div class="center">Thank you! / ස්තුතියි!</div>`;document.getElementById("modal").classList.remove("hidden")}
function closeModal(){document.getElementById("modal").classList.add("hidden")}
function pdf(){if(!window.html2pdf)return alert("PDF library not loaded");html2pdf().from(document.getElementById("receipt")).save((last?.invoice||"receipt")+".pdf")}
async function share(){let t=`SHASHA MOTORS POS\nInvoice: ${last?.invoice||""}\nTotal: Rs. ${money(last?.total)}`;if(navigator.share)try{await navigator.share({title:"Receipt",text:t})}catch{}else alert(t)}
async function scan(){let r=document.getElementById("reader");r.classList.remove("hidden");if(!window.Html5Qrcode)return alert("Scanner library not loaded");try{if(scanner)await scanner.stop().catch(()=>{});scanner=new Html5Qrcode("reader");await scanner.start({facingMode:"environment"},{fps:10,qrbox:{width:250,height:100}},code=>{document.getElementById("search").value=code;renderProducts();scanner.stop().catch(()=>{});r.classList.add("hidden")},()=>{})}catch(e){r.classList.add("hidden");alert("Camera could not start. Allow camera access in Safari.")}}
function backup(){let d={version:3,createdAt:new Date().toISOString(),products,sales,pending,invoiceCounter:Number(localStorage.getItem(IK)||0)},a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:"application/json"}));a.download="shasha-motors-pos-backup.json";a.click()}
function restoreBackup(e){let f=e.target.files?.[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);if(!confirm("Restore backup?"))return;products=d.products||[];sales=d.sales||[];pending=d.pending||[];localStorage.setItem(IK,String(d.invoiceCounter||0));save();savePending();loadLocal();alert("Backup restored")}catch{alert("Invalid backup")}};r.readAsText(f);e.target.value=""}
function loadLocal(){products=read(PK,[]);sales=read(SK,[]);pending=read(SYNC_KEY,[]);renderProducts();renderCart();renderStock();renderSales();dashboard();updateSync()}
window.addEventListener("online",()=>syncPendingSales());window.addEventListener("offline",()=>status("📴 Offline — sales stay local and will sync later","warn"));setInterval(()=>{if(navigator.onLine)syncPendingSales()},30000);
document.addEventListener("DOMContentLoaded",init);